In [1]:
print ("hello")

hello


In [2]:
2+3

5

In [4]:
x=1
if x==1:
    #indented four spaces
    print("x is 1.")

x is 1.


In [5]:
height = 1.7
weight =70
height

1.7

In [6]:
weight

70

In [10]:
weight / height ** 2

24.221453287197235

In [11]:
bmi = weight / height ** 2

In [12]:
bmi

24.221453287197235

In [13]:
type (bmi)

float

In [14]:
type ( weight)

int

In [15]:
a = "name"

In [16]:
type (a)

str

In [17]:
print (5+5)

10


In [18]:
print ( 6*6)

36


In [19]:
print (2.5/.5)

5.0


In [22]:
x = True

In [23]:
type (x)

bool

In [24]:
True + 3

4

In [25]:
False + 4

4

In [26]:
'ab'+'cd'

'abcd'

In [28]:
saving = 100
result = 100*1.5**2
print ("I started with $" + str(saving) + " and now have $" + str(result) +".Awesome!" )

I started with $100 and now have $225.0.Awesome!


In [34]:
intre = 1
y = 1000/2 
print ("initial value $" + str(intre) +" now the value is$" +str(y) )

initial value $1 now the value is$500.0


In [37]:
x=19
y =x
if (id(x)==id(y)):
    print ("x and y refer to the same object")

x and y refer to the same object


In [38]:
z = 100
if (id(y)==id(z)):
    print ("y and z point to the same memory")
else:
    print ("y and z point to the different memory")


y and z point to the different memory


In [40]:
def f1(x):
    x=x*2
    y=f2(x)
    return y
def f2(x):
    x=x+1
    return x

#main 
y=5
z=f1(y)
print (z)

11


In [41]:
fam = [1.73,2.34,3.4,1.5]
fam

[1.73, 2.34, 3.4, 1.5]

In [43]:
a= "is"
b = "nice"
my_list =["my", "list", a,b]
my_list

['my', 'list', 'is', 'nice']

In [45]:
hall=11.25
kit =18.0
liv =20.0
bed =10.75
bath =9.50

areas= [hall,kit,liv,bed,bath]

print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [46]:
areas=["hallway",hall,"kitchen",kit,"living room",liv,"bedroom",bed,"bathroom",bath]

In [47]:
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [49]:
fam=["liza",1.73,"emma",1.68,"mom",1.71,"dad",1.89]
fam

['liza', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [52]:
fam2 = [["liza",1.73],
        ["emma",1.68],
        ["mom",1.71],
        ["dad",1.89]]

fam2

[['liza', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]

In [53]:
type (fam2)

list

In [54]:
fam2[-1]

['dad', 1.89]

In [55]:
fam [-1]

1.89

In [56]:
fam[:4]

['liza', 1.73, 'emma', 1.68]

In [57]:
fam[3:]

[1.68, 'mom', 1.71, 'dad', 1.89]

In [58]:
print (areas[1])

11.25


In [59]:
print (areas[1:])

[11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [60]:
print (fam2[2:])

[['mom', 1.71], ['dad', 1.89]]


In [61]:
print (fam[1:3])

[1.73, 'emma']


In [63]:
eat_sleep_area = areas[3]+areas[7]
print ("eat_sleep_area=", eat_sleep_area)
downstairs = areas[:6]
upstairs = areas[6:]

print ("downstairs =",downstairs)
print ("upstairs =",upstairs)

eat_sleep_area= 28.75
downstairs = ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
upstairs = ['bedroom', 10.75, 'bathroom', 9.5]


In [64]:
fam[7] = 1.86

In [65]:
fam[0:2]= ["Lisa",1.74]

In [66]:
fam

['Lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [67]:
fam_ext = fam + ["me",1.79]

In [68]:
fam_ext

['Lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]

In [73]:
del(fam_ext[8])

In [74]:
fam_ext

['Lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [75]:
fam_ext =fam+["me",1.79]

In [76]:
fam_ext

['Lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]

In [80]:
x=["a","b","c"]
y=x
y[1]="z"

x

['a', 'z', 'c']

In [88]:
x=["a","b","c"]
y = list(x)
y=x[:]
y[1]="z"
x

['a', 'b', 'c']

In [91]:
areas1 =[11.25, 18.0,20.0,10.75,9.505]
areas_copy1= list(areas1)
areas_copy1[0]=5.0
print (areas1)
print (areas_copy1)

[11.25, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


In [116]:
fam.append (["me",1.79])

In [102]:
print (fam_ext)

None


In [125]:
areas1 =[11.25, 18.0,20.0,10.75,9.50]
areas1

[11.25, 18.0, 20.0, 10.75, 9.5]

In [130]:
first = (11.8,12,13,14)
round(first[0])

12

In [139]:
full_sorted = sorted(full,reverse=False)
full_sorted


[11.8, 14, 21, 22, 23, 30, 32]

In [140]:
max(full_sorted)

32

In [141]:
len(full_sorted)

7

In [152]:
x = fam.count(1.71)
y = fam.index("mom")
print ("count-occurance of 1.71=",x)
print ("index of mom=",y)

count-occurance of 1.71= 1
index of mom= 4


In [155]:
sister.capitalize()

'Liz'

In [157]:
sister.replace ("z","sa")

'lisa'

In [163]:
room = "poolhouse"
roomup=room.upper()
print (roomup)
print (room)
print (room.count("o"))

POOLHOUSE
poolhouse
3


In [181]:
areas1.reverse()
print (areas1)

[8.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [182]:
import numpy
numpy.array([1,2,3])

array([1, 2, 3])

In [183]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [5]:
r= 0.43
import math
c=2*r*math.pi
A= math.pi*r**2
print ("curcumference:" + str(c))
print ("area:" + str(A))


curcumference:2.701769682087222
area:0.5808804816487527


In [6]:
2<3

True

In [11]:
"carl" < "chris"

True

In [20]:
x= -3*6
print (x >= -10)

False


In [27]:
import numpy as np

my_house = np.array([23,24,35,12,42,9])
your_house = np.array([4,56,34,9,32,4])

print ("my_house>30", my_house > 30)
print ("my_house < your_house",my_house < your_house)

my_house>30 [False False  True False  True False]
my_house < your_house [False  True False False False False]


In [29]:
False and False

False

In [31]:
x= 8 
y = 9

not(not(x<3) and not(y>14 or y >10))

False

In [32]:
room = "kit"
areas3= 14

if room =="kit" :
    print ( "looking around the kitchen")


looking around the kitchen


In [35]:
areas3= 14

if areas3 > 15:
    print ( "big place")
else :
    print ("not a big place")

not a big place


In [37]:
room = "kit"
areas3= 14

if room =="kit" :
    print ( "looking around the kitchen")
elif areas3 > 15:
    print ( "big place")
else :
    print ("not a big place")
    

not a big place


In [53]:
#while loop
error = 50 

while error > 1:
    error = error / 4
    print (error)

12.5
3.125
0.78125


In [52]:
x = 1
while x < 4 :
        print (x) 
        x = x+1
        

1
2
3


In [57]:
areas = [11,23,43,53,12,14]
for a in areas:
    print (a)
    

11
23
43
53
12
14


In [59]:
for index, areas in enumerate (areas):
    print ("room",str(index+1),":",str(areas))

room 1 : 11
room 2 : 23
room 3 : 43
room 4 : 53
room 5 : 12
room 6 : 14


In [68]:
house = [["hallway", 11.25],
        ["Kitchen",18.0],
        ["living room",20.0],
        ["bedroom",10.75],
        ["bathroom",9.5]]
for key ,value in house:
    print ("the "+ str(key) + "is" + str(value) + " sqm")

the hallwayis11.25 sqm
the Kitchenis18.0 sqm
the living roomis20.0 sqm
the bedroomis10.75 sqm
the bathroomis9.5 sqm


In [78]:
#Dictionary
world = {"a":13,"b":2,"c":7}
world["c"]

7

In [84]:
europ ={"Spain":"madrid",
       "France":"paris",
       "Germany":"berlin",
       "Norway":"oslo"}
europ["Spain"]

'madrid'

In [86]:
print (europ.keys())

dict_keys(['Spain', 'France', 'Germany', 'Norway'])


In [88]:
world ={"a":6,"b":7,"c":8,"a":6.5}
world

{'a': 6.5, 'b': 7, 'c': 8}

In [89]:
{0:"hello",True:"dear","two":"world"}


{0: 'hello', True: 'dear', 'two': 'world'}

In [92]:
v ={("a","b"):c}
print (v.keys())

dict_keys([('a', 'b')])


In [99]:
world["a"]=9
del(world[14])

In [102]:
"a" in world

True

In [104]:
world["a"]=10
world

{'a': 10, 'b': 7, 'c': 8}

In [119]:

world["a"]=10
world

{'a': 10, 'b': 7, 'c': 8}

In [128]:
europ = {"spain":{"capital":"madrid","population":56},
      "france":{"capital": "Paris","population":32},
      "Germany":{"capital": "Berlin","population":73},
      "Norway":{"capital":"Oslo","population":83}}
print(europ["spain"]["population"])

56


In [131]:
c= {"capital":"rome","population":78}
europ["Italy"]=c
print(europ)

{'spain': {'capital': 'madrid', 'population': 56}, 'france': {'capital': 'Paris', 'population': 32}, 'Germany': {'capital': 'Berlin', 'population': 73}, 'Norway': {'capital': 'Oslo', 'population': 83}, 'Italy': {'capital': 'rome', 'population': 78}}


In [133]:
for k,v in europ.items():
    print("the capital of ",str(k), "is", str(v))

the capital of  spain is {'capital': 'madrid', 'population': 56}
the capital of  france is {'capital': 'Paris', 'population': 32}
the capital of  Germany is {'capital': 'Berlin', 'population': 73}
the capital of  Norway is {'capital': 'Oslo', 'population': 83}
the capital of  Italy is {'capital': 'rome', 'population': 78}


In [146]:
for k ,v in europ.items():
    
    for l,n in v.items():
        print ("the capital of ",str(k), "is ",str(n))
        
    

the capital of  spain is  madrid
the capital of  spain is  56
the capital of  france is  Paris
the capital of  france is  32
the capital of  Germany is  Berlin
the capital of  Germany is  73
the capital of  Norway is  Oslo
the capital of  Norway is  83
the capital of  Italy is  rome
the capital of  Italy is  78


In [154]:
height = [1,2,3,4,5,6,7]
weight = [10,20,30,40,50,60,70]
import numpy as np

np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight / np_height ** 2

In [152]:
np_height

array([1, 2, 3, 4, 5, 6, 7])

In [155]:
bmi

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667,  1.42857143])

In [156]:
np.array([1.0,True,"asskjsh"])

array(['1.0', 'True', 'asskjsh'], dtype='<U32')

In [164]:
numpy_ar = np.array([4,5,6])

In [159]:
bmi>2

array([ True,  True,  True,  True, False, False, False])

In [163]:
bmi[bmi>1.6]

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667])

In [175]:
import csv as c

with open ('details.csv' ,'r') as f:
    reader = c.reader(f)
    for row in reader:
        print (row[1])



Age
27
28
29
30
31
32
33


In [184]:
import csv
height=[]
weight=[]

with open ('baseball.csv','r') as f:
    reader = csv.reader(f)
    rowlib= 0
    for row in reader:
        if rowlib>=1:
            height.append(row[3])
            weight.append(row[4])
        rowlib=rowlib+1


        

In [205]:
height  = []
with open ('baseball.csv','r') as f:
    reader = csv.reader(f)
    l=0 
    for n in reader:
        if l != 0:
            if int(n[3]) >= 80:
                height.append(n[3])
        l=l+1
            
        
print (height)

#np_height = np_height.astype(np.float32,copy=Fase)

['81', '80', '80', '80', '80', '82', '80', '81', '82', '83']


In [196]:
type (n[3])

str

In [231]:
import csv
import numpy as np
height=[]
weight=[]
name=[]


with open ('baseball.csv','r') as f:
    reader = csv.reader(f)
    rowlib= 0
    for row in reader:
        if rowlib>=1:
            height.append(row[3])
            name.append(row[0])
            weight.append(row[4])
        rowlib=rowlib+1



#np_height = np_height.astype(np.float32,copy=Fase)
#np_weight = np_weight.astype(np.float32,copy=Fase)
np_height = np.array(height)
np_weight = np.array(weight)
np_name = np.array(name)
np_height = np_height.astype(np.float32,copy=False)
np_weight = np_weight.astype(np.float32,copy=False)
bmi = np_weight / np_height ** 2
print (bmi)

[0.03287071 0.03926224 0.04050926 ... 0.03644444 0.03377778 0.03659223]


In [227]:

type (np_height)

numpy.ndarray

In [ ]:
#append mode 'a'
# write mode 'w'


In [243]:
import csv
import numpy as np
height=[]
weight=[]
name=[]


with open ('baseball.csv','r') as f:
    reader = csv.reader(f)
    rowlib= 0
    for row in reader:
        if rowlib>=1:
            height.append(row[3])
            weight.append(row[4])
            bmi = float(row[3]) / float(row[4]) ** 2
            
            if bmi < 21:
                name.append(row[0])
                
        #name.append(row[0])
        rowlib=rowlib+1

light= np.array(name)
print (light)

#np_height = np_height.astype(np.float32,copy=Fase)
#np_weight = np_weight.astype(np.float32,copy=Fase)
#np_height = np.array(height)
#np_weight = np.array(weight)
#np_name = np.array(name)
#np_height = np_height.astype(np.float32,copy=False)
#np_weight = np_weight.astype(np.float32,copy=False)
#bmi = np_weight / np_height ** 2
#if 

    

['Adam_Donachie' 'Paul_Bako' 'Ramon_Hernandez' ... 'Chris_Narveson'
 'Randy_Keisler' 'Josh_Kinney']


In [249]:
np.logical_and(bmi > 21 , bmi <21)
logical_or() #two arguments
logical_not() # one arguments


0.0019197896120973044

In [ ]:
import numpy as np
np_height = np.array(height)
np_height[np.logical_and(np_height > 21,np_height < 50)]

In [262]:
np_height

array(['74', '74', '72', ..., '75', '75', '73'], dtype='<U2')

In [264]:
import numpy as np
for x in np_height:
    print (str(x),"inches")

74 inches
74 inches
72 inches
72 inches
73 inches
69 inches
69 inches
71 inches
76 inches
71 inches
73 inches
73 inches
74 inches
74 inches
69 inches
70 inches
73 inches
75 inches
78 inches
79 inches
76 inches
74 inches
76 inches
72 inches
71 inches
75 inches
77 inches
74 inches
73 inches
74 inches
78 inches
73 inches
75 inches
73 inches
75 inches
75 inches
74 inches
69 inches
71 inches
74 inches
73 inches
73 inches
76 inches
74 inches
74 inches
70 inches
72 inches
77 inches
74 inches
70 inches
73 inches
75 inches
76 inches
76 inches
78 inches
74 inches
74 inches
76 inches
77 inches
81 inches
78 inches
75 inches
77 inches
75 inches
76 inches
74 inches
72 inches
72 inches
75 inches
73 inches
73 inches
73 inches
70 inches
70 inches
70 inches
76 inches
68 inches
71 inches
72 inches
75 inches
75 inches
75 inches
75 inches
68 inches
74 inches
78 inches
71 inches
73 inches
76 inches
74 inches
74 inches
79 inches
75 inches
73 inches
76 inches
74 inches
74 inches
73 inches
72 inches
74 inches


In [268]:
np_2d = np.array([[1.73,1.68,1.56,1.8],
                 [65.3,34.4,43.4,54.2]])

In [273]:
np_2d.shape

(2, 4)

In [274]:
np.array([[1.73,1.68,1.56,1.8],
                 [65.3,34.4,43.4,54.2,65]])

array([list([1.73, 1.68, 1.56, 1.8]), list([65.3, 34.4, 43.4, 54.2, 65])],
      dtype=object)